version: '3.4'

services:
    catalogmongodb:
      container_name: catalogmongodb
      restart: always
      ports:
        - "27017:27017"
      volumes:
        - catalogmongo_data:/data/db
        
    catalogApi:
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
      ports:
        - "8080"
        - "8081"
    # volumes:
      # _ ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      # - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro