version: '3.4'

services:
  catalogmongodb:
    image: mongo:latest
  
  catalogApi:
    image: catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile
      
  
volumes:
  catalogmongo_data: